# Generated by Django 5.1.7 on 2025-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperienciaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
                (
                    "tipo_empleo",
                    models.CharField(max_length=100, verbose_name="Tipo de empleo"),
                ),
                (
                    "empresa",
                    models.CharField(
                        max_length=100, verbose_name="Empresa u organización"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "tipo_ubicacion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de ubicación",
                    ),
                ),
                (
                    "certificado",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificados",
                        verbose_name="Certificado",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "actualmente",
                    models.BooleanField(
                        default=False, verbose_name="Actualmente tengo este cargo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(max_length=2000, verbose_name="Descripción"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "experiencia laboral",
                "verbose_name_plural": "experiencias laborales",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
