# Generated by Django 5.1.7 on 2025-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "plataforma",
                    models.CharField(
                        help_text="Ej. Udemy, Coursera, edX...",
                        max_length=100,
                        verbose_name="Plataforma",
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Instructor"
                    ),
                ),
                (
                    "duracion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (horas)"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "enlace",
                    models.URLField(
                        blank=True, null=True, verbose_name="Enlace al curso"
                    ),
                ),
                (
                    "certificado",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificados",
                        verbose_name="Certificado",
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateField(verbose_name="Fecha de finalización"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "formacion",
                "verbose_name_plural": "formaciones",
                "ordering": ["-creado"],
            },
        ),
    ]
