# Generated by Django 5.1.7 on 2025-05-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formacion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formar",
            old_name="titulo",
            new_name="title",
        ),
    ]
