# Generated by Django 5.1.7 on 2025-05-10 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formacion", "0002_rename_titulo_formar_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formar",
            name="descripcion",
            field=ckeditor.fields.RichTextField(verbose_name="Descripción"),
        ),
    ]
