# Generated by Django 5.1.7 on 2025-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formacion", "0003_alter_formar_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormacionAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institucion",
                    models.CharField(
                        max_length=150, verbose_name="Institución educativa"
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "disciplina",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Disciplina académica",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "en_curso",
                    models.BooleanField(
                        default=False, verbose_name="¿Actualmente cursando?"
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nota"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "formación académica",
                "verbose_name_plural": "formaciones académicas",
                "ordering": ["-fecha_fin", "-fecha_inicio"],
            },
        ),
    ]
