# Generated by Django 5.1.7 on 2025-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formacion", "0004_formacionacademica"),
    ]

    operations = [
        migrations.AddField(
            model_name="formacionacademica",
            name="certificado",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="certificados",
                verbose_name="Certificado",
            ),
        ),
    ]
