# Generated by Django 5.2 on 2026-08-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[("general", "Proyecto"), ("power_bi", "Power BI")],
                default="general",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Repositorio de GitHub",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Tecnologías"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Dirección web"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha de edición"),
        ),
    ]
